name: Build index.html & Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: codeberg-tiny
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache
        uses: actions/cache@v3
        with:
          path: ci/cache
          key: ci-cache-${{ github.ref }}
          restore-keys: |
            ci-cache-${{ github.event.repository.default_branch }}

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: website

      - name: Install Package
        run: R CMD INSTALL .

      - name: Build
        run: Rscript inst/scripts/prettyStructuresTable.R

      - name: Deploy to Codeberg Pages
        uses: actions/git-pages@v2
        with:
          site: https://adafede.codeberg.page/wd-np-up-to-date/
          token: ${{ forge.token }}
          source: output/