name: Build Table
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      BUILD_TABLE:
        type: boolean
        description: generate the table
        default: true
  schedule:
    - cron: 0 0 * * * # At the end of every day
jobs:
  build_table:
    name: Build table
    runs-on: macOS-latest
    defaults:
      run:
        shell: bash --login {0}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      isPush: ${{ github.event_name == 'push' }}
    steps:
        - uses: actions/checkout@v3
        - uses: actions/cache@v3
          with:
            path: ci/cache
            key: ci-cache-${{ github.ref }}
            restore-keys: |
              ci-cache-${{ env.DEFAULT_BRANCH_REF }}
        - uses: r-lib/actions/setup-r@v2
          with:
            use-public-rspm: true
        
        - uses: r-lib/actions/setup-r-dependencies@v2
          with:
            extra-packages: any::pkgdown, local::.
            needs: website
        - name: Install Package
          run: R CMD INSTALL .
        - name: Build Table
          run: |
            Rscript inst/scripts/prettyStructuresTable.R
        - name: Create Index File
          run: |
            echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0;URL=/dev/index.html" />  <script language="javascript"> window.location.replace('/dev/index.html')</script></head></html>' > index.html
        - name: Upload Artifacts
          uses: actions/upload-artifact@v3
          with:
            name: my-artifact
            path: index.html
        - name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@main
